### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ifenice81** [mallouris/SelfServiceResetADPassword#1]
Hello

I did not find any manual to install your application (Reset Password Tool)
Potresto I say how can I install it on Windows Server 2008 step by step

Thank you

**Comment by mallouris** [comment]
Hi there,

It is necessary to download and install python 2.7 for Windows and the install the following dependencies 
pywin32, pyAD, httplib2, tornado webserver.

Search for pip install syntax on how to install easily the above packages. If you have difficulty I can create a script to automatically install the dependencies.  Just drop me an email

Regards

Mallouris

Sent from Samsung Mobile

-------- Original message --------

**Comment by mallouris** [comment]
Uploaded dependencies folder and also update the readme.rst.

**Comment by ifenice81** [comment]
Thank you
